databases:
  - name: reading_DB
    databaseName: reading_db
    user: reading_db_user
    region: singapore

services:
  - type: web
    name: reading_DB
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: reading_DB
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false