default: &default
  dapper: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Reading_Management_development

test:
  <<: *default
  database: Reading_Management_test

production:
  <<: *default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  database: books
  username: reading_db_user
  url: <%= ENV["READING_MANAGEMENT_DATABASE_PASSWORD"] %>

