default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: management_development

test:
  <<: *default
  database: management_test

production:
  <<: *default
  database: reading_db_cf35
  url: <%= ENV['DATABASE_URL'] %>
